### ISSUE TITLE
Picking up on optional dependencies.

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/assetgraph-builder-docker#2]
When running buildProduction from this package in a project using SystemJs, with a package.json containing the following:

```
{
  ...,
  "devDependency": {
    "systemjs-builder": "..."
  },
  "assetgraph-builder": {
    "outroot": "http-pub-production",
    "inputFile": "http-pub/index.html"
  }
```

The following error is thrown:

```
$ buildProduction
Guessing --root from input files: file:///app/http-pub/
 ✔ 0.000 secs: logEvents
 ✔ 0.001 secs: registerRequireJsConfig
 ✔ 0.002 secs: registerLabelsAsCustomProtocols
 ✔ 0.038 secs: loadAssets
 ✔ 0.074 secs: populate
 ✔ 0.029 secs: assumeRequireJsConfigHasBeenFound
 ✘ ERROR: Error: buildProduction transform: bundleSystemJs transform: The graph contains 2 top-level System.import calls, but systemjs-builder is not available. Please install systemjs-builder 0.14.9+ in the the containing project.
              at bundleSystemJs (/usr/local/lib/node_modules/assetgraph-builder/node_modules/assetgraph/lib/transforms/bundleSystemJs.js:549:19)
              at Object._onImmediate (/usr/local/lib/node_modules/assetgraph-builder/node_modules/assetgraph/lib/index.js:663:35)
              at processImmediate [as _immediateCallback] (timers.js:363:15)

```

This is because assetgraph-builder is installed at `/usr/local/lib/node_modules/assetgraph-builder` and thus won't pick up on the systemjs-builder present in `/app/node_modules/systemjs-builder`.

This could be solved by installing optionalDependencies in the image, but that is suboptimal, as you want it to use the version of less that you have installed in your project, not just some random version shipped with the image...

**Comment by gustavnikolaj** [comment]
@papandreou could we solve this by adding a new option to assetgraph-builder that tells it the path to check for optional dependencies?

```
$ buildProduction \
    --pathToOptionalDependencies /app/node_modules \
    --outroot /app/http-pub-production \
    /app/http-pub/index.html
```

If omitted, it defaults to the behavior of today.

**Comment by gustavnikolaj** [comment]
https://github.com/assetgraph/assetgraph/blob/0eaa1f1aaaec9f9ab3209c7c4ccb4e9400d35193/lib/transforms/bundleSystemJs.js#L547

**Comment by gustavnikolaj** [comment]
Optional dependencies in assetgraph and assetgraph-builder:

```
$ grep -C 3 -r 'try {' lib/
```

Maybe it can be done by settings `NODE_PATH` env var to `/app/node_modules/` in the docker image?
